title: "Yu Wang"
description: "PhD Candidate in Geospatial Data Science | University of Glasgow"
url: "https://ywang-twocities.github.io"

author:
  name: "Yu Wang"
  email: "y.wang.23@glasgow.ac.uk"

markdown: kramdown
theme: null
