title: "Yu Wang"
description: "PhD Candidate in Geospatial Data Science | University of Glasgow"
url: "https://ywang-twocities.github.io"

author:
  name: "Yu Wang"
  email: "y.wang.23@glasgow.ac.uk"

markdown: kramdown
theme: null

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 生成 sitemap.xml 时的基础配置
defaults:
  - scope:
      path: ""
    values:
      sitemap: true
